### ISSUE TITLE
🐛 Low priority: Remove tests from autometrics package distro

### ISSUE THREAD

**Issue by brettimus** [autometrics-dev/autometrics-ts#107]
### Environment information

```plain text
n/a
```

### What happened?

When you `npm i @auotmetrics/autometrics` and inspect `node_modules`, it seems we include our `tests` folder.

```
% ls -1 node_modules/@autometrics/autometrics
README.md
dist
package.json
reference
src
tests
tsconfig.json
tsup.config.ts
typedoc.json

```

We can use an `.npmignore` to exclude these from the package. Just need to be careful, as using `.npmignore` means npm wil no longer respect `.gitignore`

### Expected result

I wouldn't expect tests to be packaged with the autometrics library

**Comment by arendjr** [comment]
I think this should be resolved with https://github.com/autometrics-dev/autometrics-ts/pull/131 too.
