### ISSUE TITLE
Add a minimum required version of Node

### ISSUE THREAD

**Issue by keturiosakys** [autometrics-dev/autometrics-ts#109]
Some APIs we use are available or available globally only since certain, recent versions of Node. We should pin that requirement (to at least Node 16).

**Comment by arendjr** [comment]
I think this is best added to the `package.json` "skeleton" inside `build_npm.ts` now. That way it's automatically inserted into all the generated NPM packages.

We *could* also add it to the `package.json` in the root, but then `build_npm.ts` would need to extract it from there and inject it into the generated packages still.
