### ISSUE TITLE
Support applying autometrics to an object or class

### ISSUE THREAD

**Issue by emschwartz** [autometrics-dev/autometrics-ts#4]
It would be nice if you could apply autometrics to a group of functions such as:

```ts
import * as fooLibrary from "fooLibrary";
autometrics(fooLibrary);
```

or:
```ts
@Autometrics
class Foo {
  // ...
}
```

**Comment by oscarvz** [comment]
Unfortunately [it's not possible](https://www.typescriptlang.org/docs/handbook/decorators.html#class-decorators) to access the methods by decorating a class; we can only access the class' constructor.

The first suggestion is perhaps a bit of a footgun as that approach is monkey patching a whole library. Therefore I'm closing this issue.

**Comment by emschwartz** [comment]
If you access the constructor, can't you modify the `constructor.prototype`?
